# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

stages:
  - stage: DeployToVM
    jobs:
    - deployment: InstallApacheAndConfigure
      displayName: "Instalar Apache y Configurar Página"
      environment:
        name: "Grupo13VM" # Nombre de tu entorno
        resourceType: VirtualMachine # Tipo de recurso, en este caso una máquina virtual

      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                echo "Iniciando Instalación de Apache..."
                sudo apt-get update
                sudo apt-get install -y apache2
                echo "Hola Estudiantes, Hemos configurado la administración y toma de control de la máquina virtual desde Azure DevOps con código automatizado para cumplir con el CI/CD!" | sudo tee /var/www/html/index.html
                sudo systemctl restart apache2
              displayName: "Instalación y configuración completadas."
            - script: echo "Instalar Apache y Configurar Mensaje"

